#!/bin/bash
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
EM_NAME="$1"
SERVICE_NAME="$ENV_PREFIX"-"$EM_NAME"
echo "[Unit]
Description=Language model simulacrum based on Chapter 2
After=network.target
Wants=network-online.target

[Service]
Restart=always
RestartSec=3
Type=simple
WorkingDirectory=$SCRIPT_DIR
ExecStart=/usr/bin/rye run em $EM_NAME
Slice=ems-$ENV_PREFIX.slice
Environment=\"PYTHONUNBUFFERED=1\"
Environment=\"OTEL_SERVICE_NAME=$ENV_PREFIX-$EM_NAME\"

[Install]
WantedBy=default.target" > ~/.config/systemd/user/"$SERVICE_NAME".service
systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE_NAME".service
sleep 3
systemctl --user status "$SERVICE_NAME".service
