#!/bin/bash
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
EM_NAME="$1"
SERVICE_NAME="$ENV_PREFIX"-"$EM_NAME"
echo "[Unit]
Description=Chapter II em
After=network.target
Wants=network-online.target

[Service]
Restart=always
RestartSec=3s
Type=simple
WorkingDirectory=$SCRIPT_DIR
ExecStart=/usr/bin/rye run em $EM_NAME
Slice=ems-$ENV_PREFIX.slice
Environment=\"PYTHONUNBUFFERED=1\"
Environment=\"OTEL_SERVICE_NAME=$ENV_PREFIX-$EM_NAME\"
Environment=\"OTEL_BSP_SCHEDULE_DELAY=11\"
Environment=\"OTEL_EXPORTER_OTLP_TRACES_COMPRESSION=gzip\"

[Install]
WantedBy=default.target" > ~/.config/systemd/user/"$SERVICE_NAME".service
systemctl --user daemon-reload
if [[ "$#" -lt 2 ]] || [[ "$2" != "--refresh" ]]; then
  systemctl --user enable --now "$SERVICE_NAME".service
  sleep 3
  systemctl --user status "$SERVICE_NAME".service
fi
