#!/bin/bash
set -euxo pipefail
echo "Downloading and installing dependencies"
mkdir -p ../modules/
git clone https://github.com/ampdot-io/embedapi ../modules/embedapi
git clone https://github.com/ampdot-io/intermodel ../intermodel
poetry env use 3.11
poetry install
poetry shell
python3 -c "import nltk; nltk.download('punkt');"
huggingface-cli login
mkdir -p ~/.config/chapter2/
