ensembles:
 - faculty: character
   ensemble_format:
    - format: { name: irc }
      header: "The following are excerpts from Francois Arago's autobiography.\n###\n"
      footer: "###\nThis is a highly meta-aware simulation of Francois Arago.\n"
      max_tokens: 8000
      separator: "###\n"
    - format: { name: irc }
      separator: ""
      footer: ""

reply_on_random: 64
prompt_max_tokens: 31_000
recency_window: 500
continuation_max_tokens: 100
message_history_max_tokens: 10_000
#reply_on_sim: {
#  continuation_model: google/gemma-2b-GGUF
#}
stop_sequences: ["###"]
