on: [push]
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  ch2_sentry_dsn_url: ${{ secrets.ch2_sentry_dsn_url }}
  ch2_discord_token: ${{ secrets.ch2_discord_token }}
  ch2_exa_search_api_key: ${{ secrets.ch2_exa_search_api_key }}
  ch2_novelai_api_key: ${{ secrets.ch2_novelai_api_key }}
  ch2_end_to_end_test_discord_token: ${{ secrets.ch2_end_to_end_test_discord_token }}
  ch2_end_to_end_test_discord_channel_id: ${{ secrets.ch2_end_to_end_test_discord_channel_id }}
jobs:
  run-multiprong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - name: Install the project dependencies
        run: rye sync
      - name: Download punkt
        run: python3 -c "import nltk; nltk.download('wordnet'); nltk.download('punkt')"
      - name: Set secrets
        run: |
          while IFS='=' read -r -d '' n v; do
              prefix="ch2_"
              if [[ $n == $prefix* ]] ;
              then
                 key=${n#"$prefix"}
                 printf "%s: %s\n" "$key" "$v" >> ems/vendors.yaml
              fi
          done < <(env -0)
          printf "vendors: { openai: { config: { openai_api_key: %s, organization: %s } } }" >> ems/vendors.yaml
      - name: Run multiprong
        run: rye run em multiprong --end-to-end-test
