on: [push]
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
  ch2_sentry_dsn_url: ${{ secrets.ch2_sentry_dsn_url }}
  ch2_discord_token: ${{ secrets.ch2_discord_token }}
  ch2_exa_search_api_key: ${{ secrets.ch2_exa_search_api_key }}
  ch2_novelai_api_key: ${{ secrets.ch2_novelai_api_key }}
  ch2_end_to_end_test_discord_token: ${{ secrets.ch2_end_to_end_test_discord_token }}
  ch2_end_to_end_test_discord_channel_id: ${{ secrets.ch2_end_to_end_test_discord_channel_id }}
jobs:
  Run-multiprong:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.11" ]
        poetry-version: [ "1.7.1" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Download custom dependencies
        run: |
          mkdir ../modules
          git clone https://github.com/CrazyPython/intermodel ../intermodel
          git clone https://github.com/CrazyPython/embedapi ../modules/embedapi
      - name: Install the project dependencies
        run: poetry install
      - name: Download punkt
        run: poetry run python3 -c "import nltk; nltk.download('punkt')"
      - name: Set secrets
        run: |
          while IFS='=' read -r -d '' n v; do
              prefix="ch2_"
              if [[ $n == $prefix* ]] ;
              then
                 key=${n#"$prefix"}
                 printf "%s: %s\n" "$key" "$v" >> ems/vendors.yaml
              fi
          done < <(env -0)
          printf "vendors: { openai: { config: { openai_api_key: %s, organization: %s } } }" >> ems/vendors.yaml
      - name: Run multiprong
        run: poetry run python3 chapter2/main.py multiprong --end-to-end-test
